# Stage 1: Build the React frontend
FROM node:20-slim AS build

WORKDIR /app

COPY frontend/package*.json ./frontend/
RUN cd frontend && npm ci

COPY . .

# Build the React files
RUN cd frontend && npm run build

# Stage 2: Serve the static files with Nginx and setup proxying
FROM nginx:alpine

# Copy built assets from Stage 1
COPY --from=build /app/frontend/dist /usr/share/nginx/html

# Replace default configuration with custom reverse proxy configurations
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
